# fly.toml app configuration file generated for amberframework-site on 2023-10-18T04:12:27Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "amberframework-site"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
